### ISSUE TITLE
Downloading "coming soon" titles leads to an error in get_book_file_types

### ISSUE THREAD

**Issue by dan-and** [BurnhamG/packtpub-downloader#6]
Hi, 
there is a little part which is missing: If you preorder books, they will appear in your library, but are not able to download. 
Instead of getting the filetypes, you get:
{"message":"No record Found","errorCode":1001054,"errorId":"ee6bf53c-bbc6-432f-b977-e0660766768f"}

Then get_book_file_types still gets code 200, but surely no filetypes. 

Log:
https://services.packtpub.com/products-v1/products/9781788297066/types
ERROR (please copy and paste in the issue)
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main(sys.argv[1:])
  File "main.py", line 398, in main
    separate, root_directory, quiet)
  File "main.py", line 229, in download_all_books
    filenames, urls = enumerate_book_file_types(books_iter, book_file_types, root_directory, separate, user)
  File "main.py", line 267, in enumerate_book_file_types
    file_types = get_book_file_types(user, book['productId'])
  File "main.py", line 144, in get_book_file_types
    tqdm.write(r.json())
  File "/home/daniel/.local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 517, in write
    fp.write(s)
TypeError: write() argument must be str, not dict

**Comment by dan-and** [comment]
![packtpub](https://user-images.githubusercontent.com/7581653/76829868-6b81c700-6824-11ea-8f12-abc6bb13027b.png)
